### ISSUE TITLE
「Edit your Informations」の表記内容は？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#10]
![20171014_212754](https://user-images.githubusercontent.com/32208099/31575801-7e4c9482-b129-11e7-8aed-f55c7d0895a9.png)

google sheet「teacher」の「3 Edit your Informations」では、編集される内容は何でしょう？

**Comment by aikodomo** [comment]
teacher's name
Skype ID
picture?
information

**Comment by 5135a0** [comment]
1. teacher's name
1. Skype ID
1. picture
1. information

「information」って何ですか？

**Comment by aikodomo** [comment]
自己紹介です。
