### ISSUE TITLE
「Information」の表記内容は？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#11]
![20171014_220729](https://user-images.githubusercontent.com/32208099/31575949-176bc834-b12c-11e7-81fb-c7fc96ff033d.png)

google sheet「admin」の「1 Informations」の表示内容は何でしょう？

**Comment by aikodomo** [comment]
こちらは、先生たち全員が共有する連絡事項をのせたいです。
例えば、新しい生徒が入りまして、教科書は●●ですとか。
こんなクレームがありましたので、お気を付けくださいとか。

**Comment by 5135a0** [comment]
「先生全員が共有する連絡事項」

例：
- 新しい生徒の教科書は●●
- クレームの報告

これも、先生各自が「見ました・確認しました」を記録できると良いかもしれません。
