### ISSUE TITLE
「入金」と「チケット」を紐付ける必要はありますか？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#16]
現在、以下の情報を紐付けようと考えています。

1. 生徒側からの「入金」
1. 生徒の家庭が所有する「チケット」

紐付ける理由は、
どの入金から発行したチケットなのかを特定するためです。

実際のところ、紐付ける必要はありますか？

**Comment by aikodomo** [comment]
これは、どのような感じでしょうか？
例えば入金があった時点で、自動的に追加されるという事でしょうか？
それは凄い。
ただ、うちは付与されたチケットが月をまたげないので（コンスタントに受講することが一番伸びると考えているので）実際は、入金日（基本的に前月25日絞）と、チケット付与日(前月29日）がずれております。

**Comment by 5135a0** [comment]
> 入金があった時点で、自動的に追加されるという事でしょうか？

技術的には可能ですが、そこまでの機能は不要のようですね。

調べてみないと分かりませんが、そもそも、web サービスから口座へのアクセスを銀行から許可して貰う必要があるのでかなり手間だと思います。


> 付与されたチケットが月をまたげない

紐付けしないようにします。

(何か誤解があるようでしたら指摘をお願いします)

**Comment by aikodomo** [comment]
紐付けなくて大丈夫です。
