### ISSUE TITLE
「スクールからのお知らせ」に載せる内容は？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#3]
![20171014_201313](https://user-images.githubusercontent.com/32208099/31575211-58e128b4-b11c-11e7-98c5-b25a03c73556.png)

google sheet「生徒」にある「スクールからのお知らせ」に載せるべき内容は何ですか？

**Comment by aikodomo** [comment]
スクールからのお知らせは、スクールの休講情報や、規則が変わったお知らせなど
メールでお送りしている情報をこちらに表示させるということです。
メールを見た、見てないでクレームを受けるので。

**Comment by 5135a0** [comment]
「お知らせ」に載せるのは以下の項目。

1. 休講
1. 規則の変更

実例があったら、そのスクリーンショットを載せてもらえますか？
その画像の中に個人名などがあったらぼかしを入れてください。

**Comment by aikodomo** [comment]
![46](https://user-images.githubusercontent.com/32348763/32761251-ac539cf8-c935-11e7-97e9-42bbdd50218b.png)
このような形で、いつもはメールのみでお送りしています。
