### ISSUE TITLE
Lesson を決めるのに必要な情報

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#32]
Lesson を決定するための情報として以下が必要かな、と思ってますが、正しいでしょうか？

> a. 先生
> b. 生徒
> c. 日時
> d. プログラム
> e. テキストブック

プログラム (d) は、
事前に生徒 (b) とプログラム (d) を組み合わせておき、
生徒情報から紐付けられているプログラムを取り出すのだろう、と予想しています。
なので、プログラム (d) は必須ではないかもしれません。

テキストブック (e) は、
Lesson 予約時に決めるのか、それとも Lesson 毎に決めるのか、
issue #28 辺りで回答を得られると思います。

**Comment by aikodomo** [comment]
プログラムとテキストブックは連動してません。プログラムは、親子レッスン、ジュニアレッスン、大人レッスンと、年齢分けをしています。
テキストブックはその子に応じたものを、最初に決めます。

**Comment by 5135a0** [comment]
1. 先生
1. 生徒
1. 日時 (10min or 20min)
