### ISSUE TITLE
「予約画面/日別表示」の表記内容は？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#4]
![20171014_202306](https://user-images.githubusercontent.com/32208099/31575263-8b3e158c-b11d-11e7-8391-785bd585f9d1.png)

google sheet「生徒」の「2 予約画面 日別表示」にはどのような情報を載せるのでしょう？

サンプルとなるスクリーンショットがあれば、見せてもらえますか？

**Comment by aikodomo** [comment]
![37](https://user-images.githubusercontent.com/32348763/31645423-ebf51c7a-b336-11e7-8463-de0526124420.png)
![38](https://user-images.githubusercontent.com/32348763/31645424-ec286256-b336-11e7-8e65-47c551c260c9.png)
こちらになります。

**Comment by 5135a0** [comment]
日別は

- 日を指定すると
- 各先生の時刻ごとの状況が表示される
- 横軸：先生
- 縦軸：時刻

先生別は

- 横軸：日付
- 縦軸：時刻

先生別で、
表示される期間は「一週間」で固定ですか？
それとも、表示期間を伸ばしたり縮めたりできた方が良いですか？

**Comment by aikodomo** [comment]
日別は大丈夫です。
先生別は、2週間がありがたいです。
うちは1日～15日、15日～月末と予約を2回に分けてオープンします。

**Comment by 5135a0** [comment]
まとめます。

日別は

- 日を指定すると
- 各先生の時刻ごとの状況が表示される
- 横軸：先生
- 縦軸：時刻

先生別は

- 横軸：日付
- 縦軸：時刻
- 表示区間：2週間 (01-15, 15-月末)

(間違いが有りましたら指摘をお願いします)

**Comment by aikodomo** [comment]
大丈夫です。
