### ISSUE TITLE
先生が授業できないとなった場合の対処方法

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#44]
> アドミンが一人ひとり生徒に、
> この先生のこの時間で代理の先生となりますが、いかがでしょうか？
> とスカイプで連絡していて、
> 返事が来たら確定

先生が授業できないとなった場合、

運営側
>  1. その先生が担当する生徒を抽出
>  2. 何らかの方法 (*1) で先生の事情を生徒側に連絡
>  3. 代理の先生を提案

生徒側
>  a. 上記連絡手段 (*1) を閲覧
>  b. *1 上で問い合わせに回答

運営側
>  4. 回答を得る
>  5. 回答を得られない場合、....？

上記運営側の 2. で連絡される相手は

> (1) 生徒本人
> (2) 生徒の親

のどちらでしょうか？

**Comment by aikodomo** [comment]
合っています。回答を得られない場合は、代理の先生で行っています。ギリギリのキャンセルの場合は、ポイントを消費して、先生に給料を支払っています。

連絡される相手は、生徒の親もしくは大人であれば、本人です。

**Comment by 5135a0** [comment]
> 回答を得られない場合は、
> 代理の先生で行っています。

生徒側から回答が来てないので、
生徒側が連絡に気づいていない可能性がある。
もしくは回答を怠っているか。

回答されてない場合は、
運営側の都合を通して代理の先生で授業を実施。


> ギリギリのキャンセルの場合は、
> ポイントを消費して、先生に給料を支払っています。

キャンセルの時限までに連絡されていないので、
先生は授業を行う準備をしているから、
授業の直前にキャンセルされても困る。

運営側に非はないので
生徒側のポイント (チケット) を減らし、
先生は授業を行ったとみなす。


以上のように解釈しました。
間違いがあったら、修正をお願いします。

**Comment by 5135a0** [comment]
> 連絡される相手は、
> 生徒の親
> もしくは大人であれば、本人です

いずれも大人に連絡する、と。

**Comment by aikodomo** [comment]
そうですね。
