### ISSUE TITLE
連絡手段

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#45]
issue #44「何らかの方法 (*1)」としている連絡手段は、

> a. skype
> b. パソコンの email
> c. スマホの email
> d. スマホの skype
> e. スマホの LINE
  
など何が適当ですか？

**Comment by aikodomo** [comment]
今は先生はスカイプに連絡しています。

自動的に送信するとしたら、emailが良いと思います。
今、スクールからの連絡も全部emailなので。

LINEも良いと思いますが、私の方に個人的に連絡がきてしまうと、
24時間対応になってしまうので、
私とは切り離して連絡ができるものであると便利なのかもしれません。

**Comment by 5135a0** [comment]
> 1. 基本の連絡手段は skype とする
> 2. email は lolipop の上限に達しないようであれば使う
> 3. LINE は使わない

生徒側のスマホにも skype を入れてもらっていれば、LINE のように連絡付けやすいかもしれません。

LINE は電話番号と紐付いているので、切り離せないでしょうね。LINE@ という選択肢もありますが、まあ skype で十分でしょう。

**Comment by aikodomo** [comment]
スカイプ、以前に結構クレームが来まして。
みなさん、ルールは守って携帯に入れてくれるのですが、
仕事中等、アドミンからの連絡や、
先生が間違えてコールしてしまったりがあるのですが、
外国人だからなんて返答したらいいかすぐできないので、身構えてしまって
ストレスで辞めてしまうという。

なので、代理の先生は、生徒に確認なして、自動的にあてがう形で
やりたいです。嫌ならシステムからキャンセルしてくださいという。
となると一方的なemailがいいのですが、ロリポップの制限は気になりますね。
一時間に100通以上送らなけば大丈夫なので、予約の確認メールが送られなければ
大丈夫だと思います。

**Comment by 5135a0** [comment]
> 一方的なemailがいいのですが、ロリポップの制限は気になりますね。
> 一時間に100通以上送らなけば大丈夫

まずは email で作ってみましょう。

私としては、

生徒専用のページを用意し、そこに連絡が入っていて、それに応えるというやり方も取れるな、と考えています。

email だとメールボックスを見に行かなきゃいけないので、別ソフトに移動せず、単一ページでやり取りが済めば楽だな、と考えています。

**Comment by aikodomo** [comment]
なるほど　それに完結できたらいいですね
そうしましょう。

ちなみに、アプリがあると今時ですね。
連絡がきてたら携帯のアプリに①とか入ってるとか。

**Comment by 5135a0** [comment]
「アプリ風」にはできます。
スマホの native application にすると apple や google にお金払わなきゃならなくなります。

ホームページのスマホ版で十分ですよ。
