### ISSUE TITLE
10分レッスンの人の場合の予約方法

### ISSUE THREAD

**Issue by aikodomo** [5135a0/olb2#47]
20分レッスンの人は、10分のレッスンを取れないようにおねがいしましたが、
10分レッスンの人は、、2個くっつけて、20分を取れないようにしていただけますか？
今日、自由にやられている方を発見して、お断りしました。
すみませｎ

**Comment by 5135a0** [comment]
ん？

> 20分レッスンの人は、10分のレッスンを取れないように

20分のプログラムを組んでいる人には、
20分単位の授業しか選択できないようにし、

10分のプログラムを組んでいる人には、
10分単位の授業しか選択できないようにする、という仕様だったと思います。

それに追加して、

> 10分レッスンの人は、、2個くっつけて、20分を取れないようにしていただけますか？

10分のプログラムを組んでる人 (10分レッスン) は、
10分の授業を連続で組み合わせて20分の授業とみなすような選択はできないようにする、ということですか？

10分+10分で20分の授業一つと勝手にみなして、
20分の授業一つだからチケット一枚分の消費とみなして欲しい、というのをさせないようにするといういことですか？

**Comment by aikodomo** [comment]
10分の人は連続して20分に予約ができないようにして欲しいのです。
週5回の10分レッスンのプランなのに 20分 週3回 にしていたり 
当日で2回バラバラの時間で受ける事はいいけど、20分連続で受けれるなら20分のプランに変更するべきなんです。。

iPhoneから送信

2018/02/07 7:50、5135a0 <notifications@github.com>のメール:

**Comment by 5135a0** [comment]
> 10分の人は連続して20分に予約ができない

了解しました。
