### ISSUE TITLE
授業の時間構成

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#48]
先生にとって、

> 10分レッスンは、
> 10分の授業 ＋ 5分の休憩
>
> 20分レッスンは、
> 20分の授業 ＋ 10分の休憩

ですか？

**Comment by aikodomo** [comment]
そうです。
レッスン開始は　10分の人のレッスン開始時刻は　毎時　00　15　30　45分
20分の人のレッスン開始時刻は　毎時　00、30分です

**Comment by 5135a0** [comment]
了解。
プログラムに反映させます。
