### ISSUE TITLE
コースとプログラムの関係

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#53]
コースには

1. 週3
1. 週4
1. 週5

とあり、プログラムには

1. 親子
1. ジュニア
1. アダルト
1. TOEIC

とありますが、コースとプログラムの組み合わせとしては以下の様なことはありますか？

- 週3
  - 親子
  - ジュニア
- 週4
  - 親子
  - ジュニア
  - アダルト
- 週5
  - 親子
  - ジュニア
  - アダルト
  - TOEIC

プログラムはコース間で重複できない、というような制約はあるのでしょうか？

**Comment by aikodomo** [comment]
コースについてですが
1) 10分は親子のみです。
あとは、週の回数はどれを選んでもらってもいいです。

**Comment by 5135a0** [comment]
了解。
その辺、留意して修正します。

**Comment by aikodomo** [comment]
ありがとうございます。よろしくお願いします。
