### ISSUE TITLE
「生徒登録情報」の表記内容は？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#6]
google sheet「生徒」の「3 生徒登録情報」にはどのような情報を載せるのでしょう？

サンプルとなるスクリーンショットがあれば、見せてもらえますか？

**Comment by aikodomo** [comment]
ユーザー名 (user name)
名（Name）
姓(Fist Name)
親御様の名前 (parent's name)

メールアドレス(email address)
スカイプID (skype ID)
学年(grade of the school)
年齢（age)
プログラム名(program name)
追加プログラム名1（add-on1)
追加ブログラム名２(add-on2)

こちらです

**Comment by 5135a0** [comment]
年齢は時間とともに変わっていきます。

> 年齢（age)

「年齢」を「生年月日」に変更すると、プログラムで計算してその時点での年齢を表示させることができます。

「年齢」を「生年月日」に変更してはどうでしょう？

**Comment by 5135a0** [comment]
> 追加プログラム名1 (add-on1)
> 追加ブログラム名2 (add-on2)

「プログラム」という項目が別に存在するのですね。

1. 具体的にはどのような情報があり
1. どのような情報が含まれているのでしょうか？

**Comment by aikodomo** [comment]
年齢の件、とてもいい案ですね。いつも困っていました。

プログラムは
親子プログラム
ジュニアプログラム
大人プログラム
があります。
追加プログラム名はまだ未定です。

**Comment by 5135a0** [comment]
まとめます。

「年齢 (age)」を「生年月日 (birthday)」に変更しています。

生徒登録情報

1. ユーザー名 (user name)
1. 名（Name）
1. 姓 (Fist Name)
1. 親御様の名前 (parent's name)
1. メールアドレス (email address)
1. スカイプID (skype ID)
1. 学年 (grade of the school)
1. 生年月日 (birthday)
1. プログラム名 (複数) (program names)

プログラム

- 親子
- ジュニア
- 大人
- ...

(間違いが有りましたら指摘をお願いします)

**Comment by aikodomo** [comment]
とすると、学年はいらないかもしれません。
学年を入れてしまうと、3末で修正していかないといけなくなるので。
誕生日をみれはすぐ学年が分かるので。＾＾

**Comment by 5135a0** [comment]
> 7. 学年 (grade of the school)

は、「8. 生年月日 (birthday)」からの演算で求めるようにします。

**生徒登録情報**

1. ユーザー名 (user name)
1. 名（Name）
1. 姓 (Fist Name)
1. 親御様の名前 (parent's name)
1. メールアドレス (email address)
1. スカイプID (skype ID)
1. 生年月日 (birthday) _→ 学年 (grade of the school) (演算)_
1. プログラム名 (複数) (program names)

**プログラム**

- 親子
- ジュニア
- 大人
- ...
