### ISSUE TITLE
「Information」では過去の情報も載せますか？

### ISSUE THREAD

**Issue by 5135a0** [5135a0/olb2#8]
google sheet「teacher」の「1 Informations」でアドミンから送られてきた過去の連絡も一覧すべきですか？

**Comment by aikodomo** [comment]
載せたいです。先生は週１しか入らなかったり、シフト制なので確認するタイミングがまちまちなので。

**Comment by 5135a0** [comment]
過去の情報も閲覧できるようにします。

> 確認するタイミングがまちまち

情報を見たら、「読みました・確認しました」のボタンを先生達に押してもらったら良いかもしれません。

未確認の先生を絞りこめるので。

(間違いが有りましたら指摘をお願いします)

**Comment by aikodomo** [comment]
そんなことができるんですか？有難いです。
いつもアウトルックのメールで使っていた開封確認ボタンのようなものがあるといいのにな、と
思っておりました。先生が10名未満の今なら管理できるのですが、それ以上増えたらこのサービスが
ないと辛いですね。

**Comment by 5135a0** [comment]
業務用サービスでは普通そうするので、仕様として入れておきます。
